sonar.projectKey=marcelorodrigo_duty-tracker-frontend
sonar.organization=marcelorodrigo
sonar.host.url=https://sonarcloud.io
sonar.sources=app
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
